### ISSUE TITLE
Quote the string param

### ISSUE THREAD

**Issue by RatkoR** [crate/crate-pdo#26]
Hi,

the driver throws exception if anyone tries to use the [quote](https://github.com/crate/crate-pdo/blob/master/src/Crate/PDO/PDO.php#L350) method with string parameter.

Is this something that can be changed or is a no-go?

The problem is that laravel's [debugbar uses quote()](https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/QueryCollector.php#L102) methods to render the complete SQL and fails with "This is not supported" exception. It basically quotes each of the sql params and puts it back in the SQL so that the user sees full SQL.
##

**Comment by Ocramius** [comment]
This really depends on the supported escape sequences in Crate: we didn't initially implement it because there must be a VERY clear specification of how this works, or else you'll incur in SQL injection doom (not in this case, but valid for anyone using this method for actually assembling SQL strings).

**Comment by RatkoR** [comment]
You're right about the SQL injection.

Still, debugbar is quite popular. If any of them is using Crate, they get exception (even with valid SQL prepared statement). So, if you ever find time to add good escaping it'll make debugbar users happy.

Thx.

**Comment by Ocramius** [comment]
Maybe someone can look into escape sequences? @jodok?

**Comment by joemoe** [comment]
yes, we are looking at it. thanks @Ocramius

**Comment by Ocramius** [comment]
@joemoe cool! Maybe re-open the issue then? I think it is valid, just needs someone with more insight on the SQL syntax supported by Crate to look at it (and be very restrictive on allowed chars ;-) )

**Comment by joemoe** [comment]
we got some of those people here. :)

**Comment by mikethebeer** [comment]
Hi @Ocramius ,
i have added a parser test and a short lexical info about String literals to Crate master that shows how Crate is quoting strings. This file might also be interesting for you if (see https://github.com/crate/crate/blob/master/sql-parser/src/main/java/io/crate/sql/Literals.java) - it shows basically that Crate just replaces a single-quote ``'`` with doubl-single-quotes ``''``.  

However, we definitely need to talk about later if we are going to put the implementation PDO::quotes() into this driver, since it is definitely not recommend to use it.

Cheers,
Michael
